### ISSUE TITLE
Escritor de HTML no formatea bien los Type Denoters

### ISSUE THREAD

**Issue by mqbravo** [mqbravo/compiladores_1#17]
En una declaración, por ejemplo en la de un Let Command:

var x : Integer

Es espera que se escriba como:

var x : **Integer**, al ser un keyword

**Comment by mqbravo** [comment]
Se decide no implementar esta funcionalidad

**Comment by UnopposedQuill** [comment]
Resulta que Triángulo como tal define los tipos hasta el punto en el que se introduce a Checker, debido a que los tipos primitivos no se marcan usando palabras reservadas. Por este motivo es imposible para el Analizador Léxico saber si un tipo como "Integer" pertenece o no al lenguaje
