### ISSUE TITLE
Consideraciones para For Loop

### ISSUE THREAD

**Issue by mqbravo** [mqbravo/compiladores_1#25]
Hubo una consideración que no se tomó en cuenta por mi parte para la revisión del ForLoop. 
![2019-10-30_20-24](https://user-images.githubusercontent.com/33016855/67914015-8513c200-fb54-11e9-9139-d77e3fc99bc8.png)

Si esta característica se tomó en cuenta en la implementación, ignorar y cerrar el issue.

**Comment by UnopposedQuill** [comment]
Suena interesante, voy a verlo.

**Comment by UnopposedQuill** [comment]
Funciona al manejarse internamente como una variable constante.
